# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

networks:
  daala:
    external:
      name: daala


services:

  caClientAud:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.clientaud.daala.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.clientaud.daala.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/6d2076ddf2635ea18fd527df8a2ed46617a89bc02f72cdb35610e1cd6f5b5d62_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.clientaud.daala.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/3dff3ffc771d1a1f7c89bbb28aa0679c25ec51c24b4d976ef7e8e9a5f1985f1b_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/clientaud.daala.com/ca:/etc/hyperledger/fabric-ca-server-config/ca
      - ./crypto-config/peerOrganizations/clientaud.daala.com/tlsca:/etc/hyperledger/fabric-ca-server-config/tlsca
    extra_hosts:
      - caClientAud:127.0.0.1

    networks:
      daala:
        aliases:
          - ca.clientaud.daala.com
  caClientInr:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.clientinr.daala.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.clientinr.daala.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/f6f946578cf27a79ac450189088941144f11d06a445e45b1263f821674a1f384_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.clientinr.daala.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/a7ee7f21500ea21089f6ffa1775f5370c134e0a65fbf8e08ec0a69980310992e_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/clientinr.daala.com/ca:/etc/hyperledger/fabric-ca-server-config/ca
      - ./crypto-config/peerOrganizations/clientinr.daala.com/tlsca:/etc/hyperledger/fabric-ca-server-config/tlsca
    extra_hosts:
      - caClientInr:127.0.0.1

    networks:
      daala:
        aliases:
          - ca.clientinr.daala.com

  caDaalaAud:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.daalaaud.daala.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.daalaaud.daala.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/0ef8df5f3fd521dae533d696fbc9e324edf52f360633d81c5674721db92153d3_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.daalaaud.daala.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/89b01dad84394d6233f6394b9b1b0695a52c01e9cfa860e1ee05559d2cad59c9_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/daalaaud.daala.com/ca:/etc/hyperledger/fabric-ca-server-config/ca
      - ./crypto-config/peerOrganizations/daalaaud.daala.com/tlsca:/etc/hyperledger/fabric-ca-server-config/tlsca
    extra_hosts:
      - caDaalaAud:127.0.0.1

    networks:
      daala:
        aliases:
          - ca.daalaaud.daala.com

  caDaalaInr:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.daalainr.daala.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.daalainr.daala.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/148667607b0e00a1fb9b3e52270750fde720ea38247a47348ee84d33f07baf08_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.daalainr.daala.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/e8ce2659f49e0d2929fed6ce9240de1968d5c1945a37a2613c46a57299bdaf4d_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/daalainr.daala.com/ca:/etc/hyperledger/fabric-ca-server-config/ca
      - ./crypto-config/peerOrganizations/daalainr.daala.com/tlsca:/etc/hyperledger/fabric-ca-server-config/tlsca
    extra_hosts:
      - caDaalaInr:127.0.0.1

    networks:
      daala:
        aliases:
          - ca.daalainr.daala.com
