# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'


networks:
  daala:
    driver: overlay
    attachable: true


services:

  couchdb0:
    deploy:
      restart_policy:
        condition: on-failure
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - daala
  couchdb1:
    deploy:
      restart_policy:
        condition: on-failure
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
    networks:
      - daala
  couchdb2:
    deploy:
      restart_policy:
        condition: on-failure
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "7984:5984"
    networks:
      - daala
  couchdb3:
    deploy:
      restart_policy:
        condition: on-failure
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "8984:5984"
    networks:
      - daala
  couchdb4:
    deploy:
      restart_policy:
        condition: on-failure
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "9984:5984"
    networks:
      - daala
  couchdb5:
    deploy:
      restart_policy:
        condition: on-failure
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "10984:5984"
    networks:
      - daala

  couchdb6:
    deploy:
      restart_policy:
        condition: on-failure
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "11984:5984"
    networks:
      - daala
  couchdb7:
    deploy:
      restart_policy:
        condition: on-failure
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "12984:5984"
    networks:
      - daala

