NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.clientaud.daala.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.clientaud.daala.com-cert.pem
    OrganizationalUnitIdentifier: peer
