# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer0.daala.com:
    container_name: orderer0.daala.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=DaalaOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_BATCHTIMEOUT=1s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/daala.com/orderers/orderer0.daala.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/daala.com/orderers/orderer0.daala.com/tls/:/var/hyperledger/orderer/tls
    - orderer0.daala.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer1.daala.com:
    container_name: orderer1.daala.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=DaalaOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_BATCHTIMEOUT=1s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/daala.com/orderers/orderer1.daala.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/daala.com/orderers/orderer1.daala.com/tls/:/var/hyperledger/orderer/tls
    - orderer1.daala.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050

  orderer2.daala.com:
    container_name: orderer2.daala.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=DaalaOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_BATCHTIMEOUT=1s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/daala.com/orderers/orderer2.daala.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/daala.com/orderers/orderer2.daala.com/tls/:/var/hyperledger/orderer/tls
    - orderer2.daala.com:/var/hyperledger/production/orderer
    ports:
      - 9050:7050

  peer0.clientaud.daala.com:
    container_name: peer0.clientaud.daala.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.clientaud.daala.com
      - CORE_PEER_ADDRESS=peer0.clientaud.daala.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.clientaud.daala.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.clientaud.daala.com:7051
      - CORE_PEER_LOCALMSPID=ClientaudMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/clientaud.daala.com/peers/peer0.clientaud.daala.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/clientaud.daala.com/peers/peer0.clientaud.daala.com/tls:/etc/hyperledger/fabric/tls
        - peer0.clientaud.daala.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.clientaud.daala.com:
    container_name: peer1.clientaud.daala.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.clientaud.daala.com
      - CORE_PEER_ADDRESS=peer1.clientaud.daala.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.clientaud.daala.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.clientaud.daala.com:7051
      - CORE_PEER_LOCALMSPID=ClientaudMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/clientaud.daala.com/peers/peer1.clientaud.daala.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/clientaud.daala.com/peers/peer1.clientaud.daala.com/tls:/etc/hyperledger/fabric/tls
        - peer1.clientaud.daala.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.clientinr.daala.com:
    container_name: peer0.clientinr.daala.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.clientinr.daala.com
      - CORE_PEER_ADDRESS=peer0.clientinr.daala.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.clientinr.daala.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.clientinr.daala.com:7051
      - CORE_PEER_LOCALMSPID=ClientinrMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/clientinr.daala.com/peers/peer0.clientinr.daala.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/clientinr.daala.com/peers/peer0.clientinr.daala.com/tls:/etc/hyperledger/fabric/tls
        - peer0.clientinr.daala.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.clientinr.daala.com:
    container_name: peer1.clientinr.daala.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.clientinr.daala.com
      - CORE_PEER_ADDRESS=peer1.clientinr.daala.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.clientinr.daala.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.clientinr.daala.com:7051
      - CORE_PEER_LOCALMSPID=ClientinrMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/clientinr.daala.com/peers/peer1.clientinr.daala.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/clientinr.daala.com/peers/peer1.clientinr.daala.com/tls:/etc/hyperledger/fabric/tls
        - peer1.clientinr.daala.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.daalaaud.daala.com:
    container_name: peer0.daalaaud.daala.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.daalaaud.daala.com
      - CORE_PEER_ADDRESS=peer0.daalaaud.daala.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.daalaaud.daala.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.daalaaud.daala.com:7051
      - CORE_PEER_LOCALMSPID=DaalaaudMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/daalaaud.daala.com/peers/peer0.daalaaud.daala.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/daalaaud.daala.com/peers/peer0.daalaaud.daala.com/tls:/etc/hyperledger/fabric/tls
        - peer0.daalaaud.daala.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.daalaaud.daala.com:
    container_name: peer1.daalaaud.daala.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.daalaaud.daala.com
      - CORE_PEER_ADDRESS=peer1.daalaaud.daala.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.daalaaud.daala.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.daalaaud.daala.com:7051
      - CORE_PEER_LOCALMSPID=DaalaaudMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/daalaaud.daala.com/peers/peer1.daalaaud.daala.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/daalaaud.daala.com/peers/peer1.daalaaud.daala.com/tls:/etc/hyperledger/fabric/tls
        - peer1.daalaaud.daala.com:/var/hyperledger/production
    ports:
      - 14051:7051
      - 14053:7053

  peer0.daalainr.daala.com:
    container_name: peer0.daalainr.daala.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.daalainr.daala.com
      - CORE_PEER_ADDRESS=peer0.daalainr.daala.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.daalainr.daala.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.daalainr.daala.com:7051
      - CORE_PEER_LOCALMSPID=DaalainrMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/daalainr.daala.com/peers/peer0.daalainr.daala.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/daalainr.daala.com/peers/peer0.daalainr.daala.com/tls:/etc/hyperledger/fabric/tls
        - peer0.daalainr.daala.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053

  peer1.daalainr.daala.com:
    container_name: peer1.daalainr.daala.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.daalainr.daala.com
      - CORE_PEER_ADDRESS=peer1.daalainr.daala.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.daalainr.daala.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.daalainr.daala.com:7051
      - CORE_PEER_LOCALMSPID=DaalainrMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/daalainr.daala.com/peers/peer1.daalainr.daala.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/daalainr.daala.com/peers/peer1.daalainr.daala.com/tls:/etc/hyperledger/fabric/tls
        - peer1.daalainr.daala.com:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053
  ca.clientaud.daala.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.clientaud.daala.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.clientaud.daala.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/50646ba4d52b12cbc4b8925a2e38bd56e9ca98fffba6948afd805ccd18510c56_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.clientaud.daala.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/fdd5a33bcff4dbdd401215e0c94c12d7c723846d171899ca5bff26cff8f18315_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/clientaud.daala.com/ca:/etc/hyperledger/fabric-ca-server-config/ca
      - ../crypto-config/peerOrganizations/clientaud.daala.com/tlsca:/etc/hyperledger/fabric-ca-server-config/tlsca
    

  ca.daalaaud.daala.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.daalaaud.daala.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.daalaaud.daala.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/35bdbb15bdc86973cb4b8114adea57604ae0ff2e1e2e4f6c3d944e5a171b5a53_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.daalaaud.daala.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/7eff3f291d55e8431223490f0efdba6f5911d01ca508b9f62c77612900ad955c_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/daalaaud.daala.com/ca:/etc/hyperledger/fabric-ca-server-config/ca
      - ../crypto-config/peerOrganizations/daalaaud.daala.com/tlsca:/etc/hyperledger/fabric-ca-server-config/tlsca

  ca.clientinr.daala.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.clientinr.daala.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.clientinr.daala.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/9f7887ac0444609e8af14da380003ab50d7bacc9648d8feaa51bdd841032a0f4_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.clientinr.daala.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/bf83ca2efb963995ff7accb2b7f5b4d2845b672c76b8dca45b4165e3205d1aec_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/clientinr.daala.com/ca:/etc/hyperledger/fabric-ca-server-config/ca
      - ../crypto-config/peerOrganizations/clientinr.daala.com/tlsca:/etc/hyperledger/fabric-ca-server-config/tlsca
    

  ca.daalainr.daala.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.daalainr.daala.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.daalainr.daala.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/1d0bddf95b0f10c4ed9b3c92e97dee10d9e3c4975d02cc63e085e9cc5caaa652_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.daalainr.daala.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/7ae286b7378cdb8e36cc0bb5faedfd6f6606ec2fdb918ef658b079854bb93f9b_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/daalainr.daala.com/ca:/etc/hyperledger/fabric-ca-server-config/ca
      - ../crypto-config/peerOrganizations/daalainr.daala.com/tlsca:/etc/hyperledger/fabric-ca-server-config/tlsca
    
